# Generated by Django 6.0.2 on 2026-03-12 11:39

import apps.orders.models.order
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_code',
            field=models.CharField(db_index=True, default=apps.orders.models.order.generate_order_code, editable=False, max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_method',
            field=models.CharField(choices=[('pickup', 'Pickup'), ('courier', 'Courier')], default='pickup', max_length=20),
        ),
    ]
