# Generated by Django 6.0.2 on 2026-03-17 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_code',
            field=models.CharField(db_index=True, default='4P85FP', editable=False, max_length=20, unique=True),
        ),
    ]
