# Generated by Django 6.0.2 on 2026-04-03 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shop_name', models.CharField(blank=True, default="Mening do'konim", max_length=255)),
                ('order_fee', models.IntegerField(blank=True)),
                ('shop_address', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
