# Generated by Django 6.0.2 on 2026-04-03 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='order_fee',
            field=models.PositiveIntegerField(blank=True),
        ),
    ]
