# Generated by Django 6.0.2 on 2026-04-09 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='bulk_price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
