# Generated by Django 6.0.2 on 2026-03-17 11:05

import apps.catalog.models.product
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(upload_to=apps.catalog.models.product.product_image_path),
        ),
        migrations.DeleteModel(
            name='Images',
        ),
    ]
