# Generated by Django 6.0.2 on 2026-04-09 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_product_bulk_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='bulk_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
