# Generated by Django 6.0.2 on 2026-03-27 10:49

import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BotAdminContact',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('full_name', models.CharField(max_length=255)),
                ('telegram_username', models.CharField(blank=True, max_length=255)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BotSetting',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('payment_card_number', models.CharField(blank=True, max_length=64)),
                ('payment_card_owner', models.CharField(blank=True, max_length=255)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Bot setting',
                'verbose_name_plural': 'Bot settings',
            },
        ),
        migrations.CreateModel(
            name='TelegramProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('telegram_user_id', models.BigIntegerField(db_index=True, unique=True)),
                ('telegram_chat_id', models.BigIntegerField(db_index=True)),
                ('username', models.CharField(blank=True, max_length=255)),
                ('first_name', models.CharField(blank=True, max_length=255)),
                ('last_name', models.CharField(blank=True, max_length=255)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('state', models.CharField(choices=[('idle', 'Idle'), ('wait_order_code', 'Wait order code'), ('wait_receipt', 'Wait receipt'), ('wait_location', 'Wait location'), ('done', 'Done')], db_index=True, default='idle', max_length=50)),
                ('last_message_at', models.DateTimeField(blank=True, null=True)),
                ('linked_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='telegram_profiles', to='orders.order')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OrderPaymentFlow',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('waiting_receipt', 'Waiting receipt'), ('receipt_uploaded', 'Receipt uploaded'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('waiting_location', 'Waiting location'), ('delivery_started', 'Delivery started')], db_index=True, default='waiting_receipt', max_length=50)),
                ('amount_snapshot', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('card_number_snapshot', models.CharField(blank=True, max_length=64)),
                ('card_owner_snapshot', models.CharField(blank=True, max_length=255)),
                ('receipt_image', models.ImageField(blank=True, null=True, upload_to='telegram/receipts/')),
                ('receipt_file_id', models.CharField(blank=True, max_length=255)),
                ('receipt_uploaded_at', models.DateTimeField(blank=True, null=True)),
                ('location_latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('location_longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('location_received_at', models.DateTimeField(blank=True, null=True)),
                ('admin_note', models.CharField(blank=True, max_length=255)),
                ('admin_checked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checked_payment_flows', to=settings.AUTH_USER_MODEL)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment_flow', to='orders.order')),
                ('telegram_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_flows', to='telegram_bot.telegramprofile')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
