# Generated by Django 6.0.2 on 2026-03-28 07:00

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
        ('telegram_bot', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramBotAdmin',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('telegram_user_id', models.BigIntegerField(db_index=True, unique=True)),
                ('telegram_chat_id', models.BigIntegerField(db_index=True)),
                ('full_name', models.CharField(blank=True, max_length=255)),
                ('username', models.CharField(blank=True, max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('state', models.CharField(choices=[('idle', 'Idle'), ('wait_card_number', 'Wait card number'), ('wait_card_owner', 'Wait card owner'), ('wait_contact_name', 'Wait contact name'), ('wait_contact_username', 'Wait contact username'), ('wait_contact_phone', 'Wait contact phone')], db_index=True, default='idle', max_length=50)),
                ('temp_full_name', models.CharField(blank=True, max_length=255)),
                ('temp_username', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterModelOptions(
            name='botsetting',
            options={},
        ),
        migrations.RenameField(
            model_name='orderpaymentflow',
            old_name='location_received_at',
            new_name='location_uploaded_at',
        ),
        migrations.RemoveField(
            model_name='orderpaymentflow',
            name='admin_checked_by',
        ),
        migrations.RemoveField(
            model_name='orderpaymentflow',
            name='receipt_image',
        ),
        migrations.RemoveField(
            model_name='telegramprofile',
            name='last_message_at',
        ),
        migrations.RemoveField(
            model_name='telegramprofile',
            name='linked_order',
        ),
        migrations.AddField(
            model_name='telegramprofile',
            name='selected_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='telegram_selected_profiles', to='orders.order'),
        ),
        migrations.AlterField(
            model_name='orderpaymentflow',
            name='order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='telegram_payment_flow', to='orders.order'),
        ),
        migrations.AlterField(
            model_name='orderpaymentflow',
            name='status',
            field=models.CharField(choices=[('selecting_order', 'Selecting order'), ('waiting_receipt', 'Waiting receipt'), ('receipt_uploaded', 'Receipt uploaded'), ('location_uploaded', 'Location uploaded'), ('approved', 'Approved'), ('rejected', 'Rejected')], db_index=True, default='selecting_order', max_length=50),
        ),
        migrations.AlterField(
            model_name='telegramprofile',
            name='state',
            field=models.CharField(choices=[('idle', 'Idle'), ('wait_phone', 'Wait phone'), ('wait_receipt', 'Wait receipt'), ('wait_location', 'Wait location'), ('done', 'Done')], db_index=True, default='idle', max_length=50),
        ),
    ]
